version: '3.8'
services:
  ai_backend:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.ai_backend
    ports:
      - "8001:8001"
    volumes:
      - ./output:/app/output
  ui_backend:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.ui_backend
    ports:
      - "8000:8000"
    depends_on:
      - ai_backend
